OFFICES = [
    {
        "id": "admissions",
        "name": "Admissions Office",
        "block": "Block A",
        "room": "Room 101",
        "phone": "+1-800-555-0101",
        "email": "admissions@university.edu",
        "hours": "Mon–Fri: 8:00 AM – 5:00 PM",
        "services": ["Enrollment", "Transfer Credits", "Prospectus", "Application Status"],
    },
    {
        "id": "finance",
        "name": "Finance & Fees Office",
        "block": "Block B",
        "room": "Room 202",
        "phone": "+1-800-555-0202",
        "email": "finance@university.edu",
        "hours": "Mon–Fri: 9:00 AM – 4:00 PM",
        "services": ["Fee Payment", "Scholarships", "Fee Structure", "Bursaries"],
    },
    {
        "id": "examinations",
        "name": "Examinations Department",
        "block": "Block C",
        "room": "Room 305",
        "phone": "+1-800-555-0305",
        "email": "exams@university.edu",
        "hours": "Mon–Fri: 8:30 AM – 4:30 PM",
        "services": ["Results", "Transcripts", "Exam Timetables", "Supplementary Exams"],
    },
    {
        "id": "ict",
        "name": "ICT Help Desk",
        "block": "Block D",
        "room": "Room 010 (Ground Floor)",
        "phone": "+1-800-555-0010",
        "email": "ict@university.edu",
        "hours": "Mon–Fri: 7:30 AM – 6:00 PM",
        "services": ["Student Email", "Wi-Fi Access", "Software Licences", "Portal Issues"],
    },
    {
        "id": "library",
        "name": "Library & Resources",
        "block": "Main Library Building",
        "room": "All Floors",
        "phone": "+1-800-555-0500",
        "email": "library@university.edu",
        "hours": "Mon–Sat: 7:00 AM – 10:00 PM",
        "services": ["Book Loans", "Research Databases", "Study Rooms", "Printing"],
    },
    {
        "id": "welfare",
        "name": "Student Welfare",
        "block": "Student Centre",
        "room": "Room W1",
        "phone": "+1-800-555-0600",
        "email": "welfare@university.edu",
        "hours": "Mon–Fri: 8:00 AM – 5:00 PM",
        "services": ["Counselling", "Disability Support", "Health Referrals", "Bursary Applications"],
    },
    {
        "id": "accommodation",
        "name": "Accommodation Office",
        "block": "Residence Block",
        "room": "Ground Floor",
        "phone": "+1-800-555-0700",
        "email": "residence@university.edu",
        "hours": "Mon–Fri: 8:00 AM – 4:30 PM",
        "services": ["Room Allocation", "Maintenance", "Rules & Regulations", "Catering"],
    },
]

REQUIRED_DOCUMENTS = [
    {
        "category": "Registration",
        "documents": [
            "Certified copy of National ID / Passport",
            "Certified copy of Senior Certificate / Matric",
            "Proof of home address (utility bill, not older than 3 months)",
            "Passport-size photograph (2 copies)",
            "Completed registration form",
        ],
    },
    {
        "category": "Financial Aid / Bursary",
        "documents": [
            "Parent/Guardian payslip or SARS tax return",
            "Proof of income / affidavit if unemployed",
            "Completed NSFAS / bursary application form",
            "Bank statement (last 3 months)",
        ],
    },
    {
        "category": "Transcript & Certification",
        "documents": [
            "Completed transcript request form",
            "Proof of payment (transcript fee)",
            "Valid student ID card",
        ],
    },
    {
        "category": "Accommodation",
        "documents": [
            "Proof of registration / enrollment letter",
            "Proof of payment or financial guarantee",
            "Medical aid card (if applicable)",
        ],
    },
]
